on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["builder", "from-variants", "proc-macro-util", "util-impl"]

    name: "Build and Unit Test ${{ matrix.module }}"

    steps:
      - name: Check out cknittel-util
        uses: actions/checkout@v4
        with:
          path: cknittel-util
          submodules: recursive
      - name: Run unit tests
        working-directory: cknittel-util/${{ matrix.module }}
        run: |
          cargo test
      - name: Run unit tests in release mode
        working-directory: cknittel-util/${{ matrix.module }}
        run: |
          cargo test --release
      - name: Clippy lint builder
        working-directory: cknittel-util/${{ matrix.module }}
        run: |
          cargo clippy -- -D warnings
